### ISSUE TITLE
Missing some classes in package org.openclinica.ns.odm_ext_v130.v31

### ISSUE THREAD

**Issue by malajisi** [OpenClinica/OpenClinica#794]
I import master version and find some classes in package org.openclinica.ns.odm_ext_v130.v31 like OCodmComplexTypeDefinitionFormLayoutRef are missing after add ocdom project. How can I find these? Thanks.

**Comment by frissner** [comment]
Same problem here

**Comment by frissner** [comment]
seems that missing classes are in
https://github.com/OpenClinica/ocodm.git
Branch "2.3"

**Comment by malajisi** [comment]
@frissner Thanks for your guide.
